SPK_NAME = veth
SPK_VERS = 1.0
SPK_REV = 1
SPK_ICON = src/papirus-network-wired.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = jonathan-conder
DESCRIPTION = Virtual ethernet pair device
DISPLAY_NAME = Virtual ethernet
HOMEPAGE = https://kernel.org
LICENSE = GPLv2

CONF_DIR = src/conf
STARTABLE = yes
SSS_SCRIPT = src/dsm-control.sh

include ../../mk/spksrc.spk.mk
